((nil . ((eval . (add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode)))
         (eval . (add-to-list 'auto-mode-alist '("\\.uml" . python-mode)))))
 (python-mode . ((fill-column . 79)))
 (c++-mode . ((c-basic-offset . 4)
              (fill-column . 90)
              (flycheck-gcc-language-standard . "gnu++17")))))
